require('vstudio')

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
    premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
    if prj.name:find("Test") then
        premake.w('<ProjectSubType>NativeUnitTestProject</ProjectSubType>')
    end
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
    return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.globals, vcpkg)
    return calls
end)

-- Includes
IncludeDirs = {}
IncludeDirs["fmt"] = "vendor/fmt/include"

workspace "HotelManager"
    architecture "x64"

    configurations {
        "Debug",
        "Release"
    }

    startproject "HotelManager"

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

include "HotelManager"
include "HotelManagerTests"